import {Dimensions, Platform} from 'react-native';

export default {
  //participantVideo: {
  //  position: 'absolute',
  //  flex: 1,
  //  zIndex: 2,
  //  elevation: 2,
  //  width: Dimensions.get('screen').width,
  //  height: Dimensions.get('screen').height,
  //},
  remoteVideo: {
    position: 'absolute',
    width: Dimensions.get('screen').width,
    height: Dimensions.get('screen').height,
    zIndex: 1,
    elevation: 1
  },
  localVideo: {
    position: 'absolute',
    right: 5,
    top: 5,
    width: 150,
    height: 200,
    zIndex: 300,
    elevation: 300,
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  callContainer: {
    flex: 1,
    position: 'absolute',
    bottom: 0,
    top: 0,
    left: 0,
    right: 0,
  },
  welcome: {
    fontSize: 30,
    textAlign: 'center',
    paddingTop: 40,
  },
  input: {
    height: 50,
    borderWidth: 1,
    marginRight: 70,
    marginLeft: 70,
    marginTop: 50,
    textAlign: 'center',
    backgroundColor: 'white',
  },
  button: {
    marginTop: 100,
  },
  remoteOneVideo: {
    position: 'absolute',
    top: 0,
    right: 0,
    height: Dimensions.get('screen').height,
    width: Dimensions.get('screen').width,
  },
  //localVideo: {
  //  flex: 1,
  //  width: 150,
  //  height: 250,
  //  position: 'absolute',
  //  right: 10,
  //  bottom: 100,
  //},
  remoteGrid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  //remoteVideo: {
  //  marginTop: 20,
  //  marginLeft: 10,
  //  marginRight: 10,
  //  width: 100,
  //  height: 120,
  //},
  optionsContainer: {
    flex: 1,
    position: 'absolute',
    left: 0,
    top: Dimensions.get('screen').height - 210,
    //bottom: 0,
    right: 0,
    flexDirection: 'row',
    //justifyContent: 'flex-end',
    //alignItems: 'center',
    zIndex: 100,
    //backgroundColor: 'blue'
  },
  buttonText: {
    fontSize: 14,
    color: 'white',
    textAlign: 'center',
  },
  options: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10,
  },
  optionButton: {
    width: 60,
    height: 60,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 100 / 2,
    backgroundColor: '#00B33A',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    zIndex: 100,
  },
  optionButtonEnd: {
    width: 60,
    height: 60,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 100 / 2,
    backgroundColor: '#FD1111',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
};
